In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import IPython.display as ipd
import numpy as np
import pandas as pd
import librosa
import matplotlib.pyplot as plt
from scipy.io import wavfile as wav
from sklearn import metrics 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import Adam
from keras.utils import to_categorical

In [3]:
mylist = []

In [4]:
files  = librosa.util.find_files("C:/Users/Asus/Desktop/recordings/Forward",ext = ['wav'])
files = np.asarray(files)

In [5]:
for sample in files:
    sound, sample_rate = librosa.load(sample,sr=16000, res_type='kaiser_fast') 
    mfccs = librosa.feature.mfcc(y=sound, sr=sample_rate, n_mfcc=40)
    mfccs_processed = np.mean(mfccs.T,axis=0)
    mylist.append([mfccs_processed,"Forward"]) 

In [6]:
files  = librosa.util.find_files("C:/Users/Asus/Desktop/recordings/back",ext = ['wav'])
files = np.asarray(files)
for samples in files:
    sound, sample_rate = librosa.load(sample,sr=16000, res_type='kaiser_fast') 
    mfccs = librosa.feature.mfcc(y=sound, sr=sample_rate, n_mfcc=40)
    mfccs_processed = np.mean(mfccs.T,axis=0)
    mylist.append([mfccs_processed,"back"])

In [19]:
np.shape(x_train)

(128, 40)

In [20]:
x_train

array([[-271.5761    ,   86.55333   ,    7.72052   , ...,    1.6570125 ,
           6.0940447 ,    3.7466826 ],
       [-298.20422   ,   88.13896   ,   17.870667  , ...,    1.4033132 ,
           0.75138634,    1.7790425 ],
       [-298.20422   ,   88.13896   ,   17.870667  , ...,    1.4033132 ,
           0.75138634,    1.7790425 ],
       ...,
       [-298.20422   ,   88.13896   ,   17.870667  , ...,    1.4033132 ,
           0.75138634,    1.7790425 ],
       [-298.20422   ,   88.13896   ,   17.870667  , ...,    1.4033132 ,
           0.75138634,    1.7790425 ],
       [-339.3524    ,   82.88154   ,    4.8195095 , ...,    3.515793  ,
          -1.8774111 ,    1.7000136 ]], dtype=float32)

In [7]:
mylist

[[array([-3.0420499e+02,  7.1108505e+01,  1.4479812e+01,  2.4651138e+01,
         -2.6264204e+01,  2.1270721e+01,  2.1608067e-01, -1.3942115e+00,
         -1.2586381e+01, -6.2189202e+00, -5.9935455e+00,  5.4010191e+00,
         -5.3318911e+00,  5.0186291e+00, -8.6686230e+00,  5.1972675e+00,
          3.2735276e+00,  2.3863220e+00, -8.5505123e+00,  2.9178360e+00,
          1.5971179e+00,  3.1710460e+00,  1.1943429e+00,  2.4983757e+00,
          1.1631753e+00,  7.7146888e-03,  6.0827575e+00,  2.7694285e+00,
          9.9841762e-01, -1.3206422e+00,  3.7124565e+00,  3.7413807e+00,
          3.7573075e+00,  1.3496501e+00,  1.5876002e+00, -2.4307430e+00,
          1.3182406e+00,  1.3074455e-01, -2.0951331e-02, -1.4305094e+00],
        dtype=float32),
  'Forward'],
 [array([-3.32430603e+02,  9.16299896e+01,  3.38084030e+00, -2.06323552e+00,
          1.17974205e+01,  9.84254837e+00, -1.12616062e+01,  1.59682274e+01,
         -1.02169590e+01, -2.43701363e+00, -4.13165855e+00,  1.10482140e+01,


In [8]:
asDataframe = pd.DataFrame(mylist, columns=['audio_array','sound_in_word'])

In [9]:
asDataframe = asDataframe.sample(frac = 1)
asDataframe

audio_array sound_in_word
137  [-298.20422, 88.13896, 17.870667, 20.021936, 6...          back
116  [-298.20422, 88.13896, 17.870667, 20.021936, 6...          back
68   [-259.15973, 89.91292, 6.021864, 12.596819, 1....       Forward
24   [-294.14502, 88.34163, 2.6474354, 12.849697, 8...       Forward
77   [-326.70746, 71.59984, 4.3994327, 10.375426, -...       Forward
..                                                 ...           ...
76   [-276.2829, 69.16443, 1.7889701, 31.61703, -14...       Forward
95   [-298.20422, 88.13896, 17.870667, 20.021936, 6...          back
112  [-298.20422, 88.13896, 17.870667, 20.021936, 6...          back
66   [-269.39996, 84.102905, 4.688386, 19.264568, 1...       Forward
32   [-290.18814, 85.38077, -0.91827387, 18.378807,...       Forward

[160 rows x 2 columns]

In [10]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
# Convert features and corresponding classification labels into numpy arrays
X = np.array(asDataframe.audio_array.tolist())
y = np.array(asDataframe.sound_in_word.tolist())
# Encode the classification labels
label_encoder = LabelEncoder()
y = to_categorical(label_encoder.fit_transform(y))

In [11]:
# split the dataset 
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 127)

In [12]:
num_labels = y.shape[1]
model = Sequential()
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_labels))
model.add(Activation('softmax'))
# Compile the model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [13]:
from keras.callbacks import ModelCheckpoint 
from datetime import datetime 
num_epochs = 100
num_batch_size = 32
model.fit(x_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(x_test, y_test), verbose=1)

Epoch 1/100
4/4 [==============================] - 0s 45ms/step - loss: 18.4703 - accuracy: 0.4688 - val_loss: 1.9079 - val_accuracy: 0.5938
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 14.0594 - accuracy: 0.5234 - val_loss: 0.7251 - val_accuracy: 0.4688
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 9.5193 - accuracy: 0.5625 - val_loss: 2.4637 - val_accuracy: 0.4688
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 9.3200 - accuracy: 0.5234 - val_loss: 0.0345 - val_accuracy: 0.9688
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 11.8300 - accuracy: 0.5000 - val_loss: 0.0381 - val_accuracy: 1.0000
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 7.9737 - accuracy: 0.6328 - val_loss: 0.0343 - val_accuracy: 0.9688
Epoch 7/100
4/4 [==============================] - 0s 6ms/step - loss: 7.6064 - accuracy: 0.5938 - val_loss: 0.0293 - val_accuracy: 0.9688
Epoch 8/100
4/4 [======

Epoch 59/100
4/4 [==============================] - 0s 9ms/step - loss: 0.2699 - accuracy: 0.9609 - val_loss: 0.0823 - val_accuracy: 0.9688
Epoch 60/100
4/4 [==============================] - 0s 6ms/step - loss: 0.2172 - accuracy: 0.9766 - val_loss: 0.1250 - val_accuracy: 0.9688
Epoch 61/100
4/4 [==============================] - 0s 5ms/step - loss: 0.3051 - accuracy: 0.9531 - val_loss: 0.1013 - val_accuracy: 0.9688
Epoch 62/100
4/4 [==============================] - 0s 5ms/step - loss: 0.3120 - accuracy: 0.9766 - val_loss: 0.0476 - val_accuracy: 0.9688
Epoch 63/100
4/4 [==============================] - 0s 5ms/step - loss: 0.4066 - accuracy: 0.9688 - val_loss: 0.0252 - val_accuracy: 0.9688
Epoch 64/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1379 - accuracy: 0.9609 - val_loss: 0.0216 - val_accuracy: 1.0000
Epoch 65/100
4/4 [==============================] - 0s 6ms/step - loss: 0.2470 - accuracy: 0.9766 - val_loss: 0.0184 - val_accuracy: 1.0000
Epoch 66/100
4/4 [==

In [78]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (32, 256)                 10496     
_________________________________________________________________
activation_9 (Activation)    (32, 256)                 0         
_________________________________________________________________
dropout_6 (Dropout)          (32, 256)                 0         
_________________________________________________________________
dense_11 (Dense)             (32, 256)                 65792     
_________________________________________________________________
activation_10 (Activation)   (32, 256)                 0         
_________________________________________________________________
dropout_7 (Dropout)          (32, 256)                 0         
_________________________________________________________________
dense_12 (Dense)             (32, 2)                  

score = model.evaluate(x_test, y_test, verbose=0)
accuracy = 100*score[1]
accuracy

In [79]:
# Calculate pre-training accuracy 
score = model.evaluate(x_test, y_test, verbose=0)
accuracy = 100*score[1]

In [80]:
accuracy

96.875

In [81]:
model.predict(x_test)

array([[1.22691180e-11, 1.00000000e+00],
       [1.00000000e+00, 5.11475831e-14],
       [1.00000000e+00, 8.16701723e-18],
       [1.22691180e-11, 1.00000000e+00],
       [1.00000000e+00, 3.70746374e-16],
       [1.00000000e+00, 9.31786662e-11],
       [1.22691180e-11, 1.00000000e+00],
       [1.22691180e-11, 1.00000000e+00],
       [1.22691180e-11, 1.00000000e+00],
       [1.00000000e+00, 2.19168437e-14],
       [1.00000000e+00, 4.00821748e-17],
       [1.00000000e+00, 1.47427016e-14],
       [1.22691180e-11, 1.00000000e+00],
       [1.00000000e+00, 4.38563113e-13],
       [1.00000000e+00, 1.92635052e-13],
       [1.00000000e+00, 8.25325919e-13],
       [1.22691180e-11, 1.00000000e+00],
       [1.00000000e+00, 7.96542174e-18],
       [1.22691180e-11, 1.00000000e+00],
       [1.22691180e-11, 1.00000000e+00],
       [1.00000000e+00, 9.04336848e-12],
       [1.22691180e-11, 1.00000000e+00],
       [1.00000000e+00, 7.41659895e-20],
       [1.00000000e+00, 2.17778292e-18],
       [1.226911

In [82]:
y_test

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [83]:
y_test

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [84]:
score = model.evaluate(x_test, model.predict(x_test), verbose=0)
accuracy = 100*score[1]

In [85]:
accuracy

100.0

In [86]:
y_pred = model.predict(x_test)

In [87]:
np.around(y_pred, decimals=0, out=None)

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [88]:
y_test

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [16]:
x_train[0]

array([-2.7157611e+02,  8.6553329e+01,  7.7205200e+00,  1.7962330e+01,
       -1.4992949e+00,  1.1137708e+01, -1.0097946e+01,  1.2892616e+01,
       -4.1985016e+00, -6.5607816e-02,  3.0700159e+00,  2.8357456e+00,
       -3.8493829e+00,  8.0371552e+00, -4.3346043e+00,  4.8115649e+00,
       -6.6362801e+00,  1.8451754e+00, -5.9919338e+00, -2.1005840e+00,
       -5.1100578e+00, -1.9255701e+00, -1.4518199e+00,  1.0788872e+00,
        6.7905903e-02,  3.3097677e+00,  4.6707538e-01,  1.3963639e+00,
        3.4736164e+00,  3.3230016e+00,  2.4117846e+00,  4.3539753e+00,
        6.5062299e+00,  6.3978920e+00,  5.8592248e+00,  5.8151331e+00,
        3.7704017e+00,  1.6570125e+00,  6.0940447e+00,  3.7466826e+00],
      dtype=float32)

In [17]:
asDataframe

audio_array sound_in_word
137  [-298.20422, 88.13896, 17.870667, 20.021936, 6...          back
116  [-298.20422, 88.13896, 17.870667, 20.021936, 6...          back
68   [-259.15973, 89.91292, 6.021864, 12.596819, 1....       Forward
24   [-294.14502, 88.34163, 2.6474354, 12.849697, 8...       Forward
77   [-326.70746, 71.59984, 4.3994327, 10.375426, -...       Forward
..                                                 ...           ...
76   [-276.2829, 69.16443, 1.7889701, 31.61703, -14...       Forward
95   [-298.20422, 88.13896, 17.870667, 20.021936, 6...          back
112  [-298.20422, 88.13896, 17.870667, 20.021936, 6...          back
66   [-269.39996, 84.102905, 4.688386, 19.264568, 1...       Forward
32   [-290.18814, 85.38077, -0.91827387, 18.378807,...       Forward

[160 rows x 2 columns]