In [1]:
import librosa as lb
import librosa.display as disp
import numpy as np
import matplotlib.pyplot as plt


## Understanding the audio

In [2]:
files = lb.util.find_files("C:/Users/Asus/Desktop/recordings/Forward",ext = ['wav'])
files = np.asarray(files)
for sample in files:
    x = lb.load(sample,sr = 16000)
    x = x[0]
    #plt.figure(figsize=(12,4))
    #lb.display.waveplot(x, sr=16000)
    #X = lb.stft(x)
    #Xdb = lb.amplitude_to_db(abs(X))
    #plt.figure(figsize=(20, 5))
    #lb.display.specshow(Xdb, sr=16000, x_axis='time', y_axis='hz')
    #plt.colorbar()

## preprocessing of audio signals

In [3]:
for sample in files:
    x = lb.load(sample,sr = 16000)
    x = x[0]
    #plt.figure(figsize = (14,7))
    #lb.display.waveplot(x,sr=16000)

In [4]:
import sklearn.preprocessing as skl

## getting things into an array

In [5]:
name = "recording0.wav"
x = lb.load(name,sr=16000)
x = x[0]
print(type(x))
audio = np.empty(80,dtype = type(x))

<class 'numpy.ndarray'>


In [6]:
i = 0
for sample in files:
    x = lb.load(sample,sr=16000)
    x = x[0]
    audio[i] = x
    i = i+1
i = 0

In [7]:
print(audio)

[array([0.0585022 , 0.0585022 , 0.05838013, ..., 0.06225586, 0.0256958 ,
       0.0440979 ], dtype=float32)
 array([0.10443115, 0.10443115, 0.10430908, ..., 0.10391235, 0.10003662,
       0.09817505], dtype=float32)
 array([0.20562744, 0.20562744, 0.20544434, ..., 0.20272827, 0.20968628,
       0.20562744], dtype=float32)
 array([0.06454468, 0.06454468, 0.06442261, ..., 0.2111206 , 0.19592285,
       0.17651367], dtype=float32)
 array([0.05352783, 0.05352783, 0.05328369, ..., 0.05566406, 0.05969238,
       0.05447388], dtype=float32)
 array([0.08288574, 0.08288574, 0.08267212, ..., 0.08361816, 0.06921387,
       0.07275391], dtype=float32)
 array([0.02816772, 0.02816772, 0.02789307, ..., 0.06253052, 0.05142212,
       0.04031372], dtype=float32)
 array([0.07168579, 0.07168579, 0.07147217, ..., 0.07629395, 0.08590698,
       0.08737183], dtype=float32)
 array([0.09692383, 0.09692383, 0.09674072, ..., 0.1267395 , 0.11584473,
       0.11102295], dtype=float32)
 array([-0.12658691, -0.1265

In [8]:
for i in range(0,80):
    skl.minmax_scale(audio[i],axis = 0)
    

In [9]:
print(audio)

[array([0.0585022 , 0.0585022 , 0.05838013, ..., 0.06225586, 0.0256958 ,
       0.0440979 ], dtype=float32)
 array([0.10443115, 0.10443115, 0.10430908, ..., 0.10391235, 0.10003662,
       0.09817505], dtype=float32)
 array([0.20562744, 0.20562744, 0.20544434, ..., 0.20272827, 0.20968628,
       0.20562744], dtype=float32)
 array([0.06454468, 0.06454468, 0.06442261, ..., 0.2111206 , 0.19592285,
       0.17651367], dtype=float32)
 array([0.05352783, 0.05352783, 0.05328369, ..., 0.05566406, 0.05969238,
       0.05447388], dtype=float32)
 array([0.08288574, 0.08288574, 0.08267212, ..., 0.08361816, 0.06921387,
       0.07275391], dtype=float32)
 array([0.02816772, 0.02816772, 0.02789307, ..., 0.06253052, 0.05142212,
       0.04031372], dtype=float32)
 array([0.07168579, 0.07168579, 0.07147217, ..., 0.07629395, 0.08590698,
       0.08737183], dtype=float32)
 array([0.09692383, 0.09692383, 0.09674072, ..., 0.1267395 , 0.11584473,
       0.11102295], dtype=float32)
 array([-0.12658691, -0.1265

## now premphasizeing the signals

In [53]:
import keras

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, Conv2D, MaxPooling2D, GlobalAveragePooling2D
from keras.optimizers import Adam
from keras.utils import np_utils
from sklearn import metrics

In [11]:
import pandas as pd
Y = pd.read_csv("Book1.csv")

In [12]:
Y = Y.iloc[:,:].values

In [13]:
print(Y)

[['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']
 ['forward']

In [14]:
import tensorflow as tf

In [15]:
print(audio)

[array([0.0585022 , 0.0585022 , 0.05838013, ..., 0.06225586, 0.0256958 ,
       0.0440979 ], dtype=float32)
 array([0.10443115, 0.10443115, 0.10430908, ..., 0.10391235, 0.10003662,
       0.09817505], dtype=float32)
 array([0.20562744, 0.20562744, 0.20544434, ..., 0.20272827, 0.20968628,
       0.20562744], dtype=float32)
 array([0.06454468, 0.06454468, 0.06442261, ..., 0.2111206 , 0.19592285,
       0.17651367], dtype=float32)
 array([0.05352783, 0.05352783, 0.05328369, ..., 0.05566406, 0.05969238,
       0.05447388], dtype=float32)
 array([0.08288574, 0.08288574, 0.08267212, ..., 0.08361816, 0.06921387,
       0.07275391], dtype=float32)
 array([0.02816772, 0.02816772, 0.02789307, ..., 0.06253052, 0.05142212,
       0.04031372], dtype=float32)
 array([0.07168579, 0.07168579, 0.07147217, ..., 0.07629395, 0.08590698,
       0.08737183], dtype=float32)
 array([0.09692383, 0.09692383, 0.09674072, ..., 0.1267395 , 0.11584473,
       0.11102295], dtype=float32)
 array([-0.12658691, -0.1265

In [16]:
dataframe = pd.DataFrame(audio[0])
dataframe[0] = pd.DataFrame(audio[0])
for i in range(1,80):
    dataframe[i] = pd.DataFrame(audio[i])

In [17]:
dataframe

0         1         2         3         4         5         6   \
0      0.058502  0.104431  0.205627  0.064545  0.053528  0.082886  0.028168   
1      0.058502  0.104431  0.205627  0.064545  0.053528  0.082886  0.028168   
2      0.058380  0.104309  0.205444  0.064423  0.053284  0.082672  0.027893   
3      0.058502  0.104431  0.205627  0.064545  0.053528  0.082886  0.028168   
4      0.058502  0.104431  0.205627  0.064545  0.053528  0.082886  0.028168   
...         ...       ...       ...       ...       ...       ...       ...   
15995  0.045258  0.107513  0.218201  0.236877  0.048523  0.066620  0.033844   
15996  0.075256  0.104431  0.202332  0.232513  0.049469  0.073944  0.051666   
15997  0.062256  0.103912  0.202728  0.211121  0.055664  0.083618  0.062531   
15998  0.025696  0.100037  0.209686  0.195923  0.059692  0.069214  0.051422   
15999  0.044098  0.098175  0.205627  0.176514  0.054474  0.072754  0.040314   

             7         8         9   ...        70        71        72  \
0      0.071686  0.096924 -0.126587  ...  0.167664  0.125488  0.181519   
1      0.071686  0.096924 -0.126587  ...  0.167664  0.125488  0.181519   
2      0.071472  0.096741 -0.126801  ...  0.167419  0.125214  0.181274   
3      0.071686  0.096924 -0.126587  ...  0.167664  0.125488  0.181519   
4      0.071686  0.096924 -0.126587  ...  0.167664  0.125488  0.181519   
...         ...       ...       ...  ...       ...       ...       ...   
15995  0.082336  0.122803 -0.142975  ...  0.190033  0.139526  0.173462   
15996  0.075867  0.127960 -0.137512  ...  0.191040  0.127045  0.179077   
15997  0.076294  0.126740 -0.132446  ...  0.182251  0.133820  0.161255   
15998  0.085907  0.115845 -0.130035  ...  0.180969  0.125763  0.136597   
15999  0.087372  0.111023 -0.110992  ...  0.190033  0.122375  0.221313   

             73        74        75        76        77        78        79  
0      0.197449  0.113953  0.062073  0.110046  0.093994  0.100006  0.121033  
1      0.197449  0.113953  0.062073  0.110046  0.093994  0.100006  0.121033  
2      0.197266  0.113708  0.061646  0.109833  0.093811  0.099823  0.120819  
3      0.197449  0.113953  0.062073  0.110046  0.093994  0.100006  0.121033  
4      0.197449  0.113953  0.062073  0.110046  0.093994  0.100006  0.121033  
...         ...       ...       ...       ...       ...       ...       ...  
15995  0.205536  0.119934  0.027863  0.125397  0.115784  0.096985  0.121704  
15996  0.205536  0.118439  0.014771  0.140137  0.108948  0.103638  0.121704  
15997  0.205353  0.129669  0.000824  0.138275  0.104614  0.109711  0.128876  
15998  0.205750  0.133911  0.021515  0.098419  0.101471  0.103058  0.129791  
15999  0.204956  0.129181  0.024048  0.067474  0.094147  0.094696  0.131348  

[16000 rows x 80 columns]

In [18]:
dataframe = dataframe.T

In [19]:
dataframe

0         1         2         3         4         5         6      \
0   0.058502  0.058502  0.058380  0.058502  0.058502  0.058502  0.058502   
1   0.104431  0.104431  0.104309  0.104431  0.104431  0.104431  0.104431   
2   0.205627  0.205627  0.205444  0.205627  0.205627  0.205627  0.205627   
3   0.064545  0.064545  0.064423  0.064545  0.064545  0.064545  0.064545   
4   0.053528  0.053528  0.053284  0.053528  0.053528  0.053528  0.053528   
..       ...       ...       ...       ...       ...       ...       ...   
75  0.062073  0.062073  0.061646  0.062073  0.062073  0.062073  0.062073   
76  0.110046  0.110046  0.109833  0.110046  0.110046  0.110046  0.110046   
77  0.093994  0.093994  0.093811  0.093994  0.093994  0.093994  0.093994   
78  0.100006  0.100006  0.099823  0.100006  0.100006  0.100006  0.100006   
79  0.121033  0.121033  0.120819  0.121033  0.121033  0.121033  0.121033   

       7         8         9      ...     15990     15991     15992     15993  \
0   0.058380  0.058502  0.058502  ...  0.039764  0.072083  0.073486  0.062134   
1   0.104309  0.104431  0.104431  ...  0.096191  0.098724  0.103119  0.104980   
2   0.205444  0.205627  0.205627  ...  0.201569  0.205048  0.210449  0.203705   
3   0.064423  0.064545  0.064545  ...  0.311005  0.294556  0.277802  0.263885   
4   0.053284  0.053528  0.053528  ...  0.042328  0.045654  0.049011  0.044006   
..       ...       ...       ...  ...       ...       ...       ...       ...   
75  0.061646  0.062073  0.062073  ...  0.110199  0.094574  0.078522  0.066284   
76  0.109833  0.110046  0.110046  ...  0.111267  0.123108  0.126038  0.119995   
77  0.093811  0.093994  0.093994  ...  0.082489  0.090820  0.102478  0.108948   
78  0.099823  0.100006  0.100006  ...  0.106293  0.095459  0.093933  0.093750   
79  0.120819  0.121033  0.121033  ...  0.123505  0.133820  0.135376  0.129791   

       15994     15995     15996     15997     15998     15999  
0   0.040802  0.045258  0.075256  0.062256  0.025696  0.044098  
1   0.108154  0.107513  0.104431  0.103912  0.100037  0.098175  
2   0.215881  0.218201  0.202332  0.202728  0.209686  0.205627  
3   0.245728  0.236877  0.232513  0.211121  0.195923  0.176514  
4   0.042084  0.048523  0.049469  0.055664  0.059692  0.054474  
..       ...       ...       ...       ...       ...       ...  
75  0.044739  0.027863  0.014771  0.000824  0.021515  0.024048  
76  0.113556  0.125397  0.140137  0.138275  0.098419  0.067474  
77  0.111938  0.115784  0.108948  0.104614  0.101471  0.094147  
78  0.090149  0.096985  0.103638  0.109711  0.103058  0.094696  
79  0.126190  0.121704  0.121704  0.128876  0.129791  0.131348  

[80 rows x 16000 columns]

In [20]:
X = dataframe.iloc[:,:].values

In [21]:
X

array([[0.0585022 , 0.0585022 , 0.05838013, ..., 0.06225586, 0.0256958 ,
        0.0440979 ],
       [0.10443115, 0.10443115, 0.10430908, ..., 0.10391235, 0.10003662,
        0.09817505],
       [0.20562744, 0.20562744, 0.20544434, ..., 0.20272827, 0.20968628,
        0.20562744],
       ...,
       [0.09399414, 0.09399414, 0.09381104, ..., 0.10461426, 0.10147095,
        0.09414673],
       [0.1000061 , 0.1000061 , 0.099823  , ..., 0.10971069, 0.10305786,
        0.09469604],
       [0.12103271, 0.12103271, 0.12081909, ..., 0.12887573, 0.12979126,
        0.13134766]], dtype=float32)

In [22]:
from sklearn.model_selection import train_test_split

In [73]:
x_train,x_text, y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 0)

In [74]:
np.shape(x_train)

(64, 16000)

In [75]:
x_train = np.expand_dims(x_train, axis=0)

x_text = np.expand_dims(x_text, axis=0)



In [87]:
y_train = np.reshape()
y_test = np.reshape(1,10)


ValueError: cannot reshape array of size 1 into shape (10,)

In [84]:

x_train = x_train.reshape(10,10,10,1024)
x_text =x_text.reshape(10,10,10,256)

In [85]:
#Define Model
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(64,16000,10)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())

model.add(Dropout(0.5))
model.add(Dense(4, activation='softmax'))
#Compile
model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adam(), metrics=['accuracy'])
print(model.summary())
#Train and Test The Model
model.fit(x_train, y_train, batch_size=4, epochs=10, verbose=1, validation_data=(x_text, y_test))

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_36 (Conv2D)           (None, 62, 15998, 32)     2912      
_________________________________________________________________
conv2d_37 (Conv2D)           (None, 60, 15996, 64)     18496     
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 30, 7998, 64)      0         
_________________________________________________________________
dropout_17 (Dropout)         (None, 30, 7998, 64)      0         
_________________________________________________________________
flatten_10 (Flatten)         (None, 15356160)          0         
_________________________________________________________________
dropout_18 (Dropout)         (None, 15356160)          0         
_________________________________________________________________
dense_9 (Dense)              (None, 4)               

ValueError: Data cardinality is ambiguous:
  x sizes: 10
  y sizes: 1
Please provide data which shares the same first dimension.

In [53]:
train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train))
valid_data = tf.data.Dataset.from_tensor_slices((x_text, y_test))



In [54]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
model.fit(x_train,y_train)
# Display model architecture summary 
model.summary()

# Calculate pre-training accuracy 
score = model.evaluate(x_text, y_test, verbose=1)
accuracy = 100*score[1]

print("Pre-training accuracy: %.4f%%" % accuracy) 

ValueError: in user code:

    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\engine\training.py:747 train_step
        y_pred = self(x, training=True)
    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\Asus\anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:191 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_12 is incompatible with the layer: : expected min_ndim=4, found ndim=2. Full shape received: [32, 16000]


In [ ]:
print(audio[1])

In [45]:
np.shape(x_train)

(64, 16000)

In [ ]:
tf.convert_to_tensor(audio)

In [ ]:
np.shape(audio[6])

In [ ]:
audiodf = pd.DataFrame(audio[:,:])

In [ ]:
audiodf

In [ ]:
audio = audiodf.iloc[:,:].values

In [ ]:
audio